/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perceptronmain;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * @author Marco Gonzalez
 */
public class PFrame extends javax.swing.JFrame {

    /**
     * Creates new form PFrame
     */
    PatternList pList = new PatternList();
    InputList iList = new InputList();
    int i = 1; // For testing

    public PFrame() {
        initComponents();
        setVisible(true);
        setSize(340, 555);
        updateButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        selectButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        thetaField = new javax.swing.JTextField();
        etaField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dirLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 170, 280, 310);

        selectButton.setText("Select File...");
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButtonActionPerformed(evt);
            }
        });
        getContentPane().add(selectButton);
        selectButton.setBounds(10, 80, 140, 30);

        jLabel1.setFont(new java.awt.Font("Unispace", 1, 48)); // NOI18N
        jLabel1.setText("Perceptron");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 330, 80);

        updateButton.setText("Experiment");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateButton);
        updateButton.setBounds(160, 80, 100, 30);

        thetaField.setText("10000");
        thetaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thetaFieldActionPerformed(evt);
            }
        });
        getContentPane().add(thetaField);
        thetaField.setBounds(150, 120, 100, 30);

        etaField.setText("1");
        etaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etaFieldActionPerformed(evt);
            }
        });
        getContentPane().add(etaField);
        etaField.setBounds(10, 120, 100, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("θ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 100, 10, 60);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("η");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 110, 20, 40);

        dirLabel.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        getContentPane().add(dirLabel);
        dirLabel.setBounds(10, 480, 280, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButtonActionPerformed
        FileManager fmObj = new FileManager();
        File f = fmObj.selectFile();
        pList.clear();
        iList.clear();
        updateButton.setVisible(true);

        if (f.isFile()) {
            Pattern ha;
            try {
                ha = new Pattern(f);
                textArea.setText(ha.toString());
            } catch (IOException ex) {
                textArea.setText("FILE NOT FOUND!");
            }
        } else if (f.isDirectory()) {
            ArrayList<File> filesInDirectory = new ArrayList<>(Arrays.asList(f.listFiles()));
            dirLabel.setText("Current Directory: " + f.getAbsolutePath());
            
            for (int i = 0; i < filesInDirectory.size(); i++) {
                try {
                    Pattern p = new Pattern(filesInDirectory.get(i));
                    Input in = new Input(p);
                    iList.add(in);
                    pList.add(p);
                } catch (IOException ex) {

                    textArea.setText("FILE NOT FOUND!");

                } // End of try catch

            } // End of foreach file in directory

            Ptron p = new Ptron(iList);
            if (!thetaField.getText().equals("")) {
                p.setTheta(Integer.parseInt(thetaField.getText()));
            }

            if (!etaField.getText().equals("")) {
                p.setEta(Integer.parseInt(etaField.getText()));
            }

            p.training();
            textArea.setText(p.toString());

        } // End of if else (is file or dir)
    }//GEN-LAST:event_selectButtonActionPerformed

    private void etaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etaFieldActionPerformed

    private void thetaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thetaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thetaFieldActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        if (!iList.isEmpty()) {
            Ptron p = new Ptron(iList);
            if (!thetaField.getText().equals("")) {
                p.setTheta(Integer.parseInt(thetaField.getText()));
            }

            if (!etaField.getText().equals("")) {
                p.setEta(Integer.parseInt(etaField.getText()));
            }

            p.training();
            textArea.setText(p.toString());
        } else {
            textArea.setText("No file selected");
        }


    }//GEN-LAST:event_updateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dirLabel;
    private javax.swing.JTextField etaField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton selectButton;
    private javax.swing.JTextArea textArea;
    private javax.swing.JTextField thetaField;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
