/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perceptronmain;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * @author Marco Gonzalez
 */
public class PFrame extends javax.swing.JFrame {

    /**
     * Creates new form PFrame
     */
    PatternList pList = new PatternList();
    InputList iList = new InputList();
    int i = 1; // For testing

    public PFrame() {
        initComponents();
        setVisible(true);
        setSize(510, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        selectButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        theta = new javax.swing.JTextField();
        ata = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 130, 470, 420);

        selectButton.setText("Select File...");
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButtonActionPerformed(evt);
            }
        });
        getContentPane().add(selectButton);
        selectButton.setBounds(10, 90, 120, 30);

        jLabel1.setFont(new java.awt.Font("Unispace", 1, 48)); // NOI18N
        jLabel1.setText("Perceptron");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 330, 80);

        saveButton.setText("Next");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveButton);
        saveButton.setBounds(140, 90, 100, 30);

        theta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thetaActionPerformed(evt);
            }
        });
        getContentPane().add(theta);
        theta.setBounds(390, 90, 50, 30);

        ata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ataActionPerformed(evt);
            }
        });
        getContentPane().add(ata);
        ata.setBounds(310, 90, 50, 30);

        jLabel2.setText("θ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(450, 80, 10, 40);

        jLabel3.setText("η");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(370, 90, 20, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButtonActionPerformed
        FileManager fmObj = new FileManager();
        File f = fmObj.selectFile();
        pList.clear();
        iList.clear();

        if (f.isFile()) {
            Pattern ha;
            try {
                ha = new Pattern(f);
                textArea.setText(ha.toString());
            } catch (IOException ex) {
                textArea.setText("FILE NOT FOUND!");
            }
        } else if (f.isDirectory()) {
            ArrayList<File> filesInDirectory = new ArrayList<>(Arrays.asList(f.listFiles()));

            for (int i = 0; i < filesInDirectory.size(); i++) {
                try {
                    Pattern p = new Pattern(filesInDirectory.get(i));
                    Input in = new Input(p);
                    iList.add(in);
                    pList.add(p);
                } catch (IOException ex) {
                    textArea.setText("FILE NOT FOUND!");
                } // End of try catch
            } // End of foreach file in directory
            textArea.setText(iList.get(0).toString());
            
            Ptron p = new Ptron(iList);
            p.training(); 
        } // End of if else (is file or dir)
    }//GEN-LAST:event_selectButtonActionPerformed

    private void ataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ataActionPerformed

    private void thetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thetaActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if (!iList.isEmpty()) {
            textArea.setText(iList.get(i).toString());
            i++;
        } else {
            textArea.setText("The list is empty");
        }

    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton selectButton;
    private javax.swing.JTextArea textArea;
    private javax.swing.JTextField theta;
    // End of variables declaration//GEN-END:variables
}
